// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-project-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_project_info_default = defineTool({
  name: "get_project_info",
  title: "Get project info",
  description: "Return overview of the Erasmus+ project 'LATER IS TOO LATE: SAY NO TO OBESITY NOW', including code, dates, coordinator, aims, and website.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      title: "LATER IS TOO LATE: SAY NO TO OBESITY NOW",
      programme: "Erasmus+ KA210-SCH Small-scale partnerships in school education",
      project_code: "2024-2-FR01-KA210-SCH-000279027",
      duration: "March 2025 \u2013 July 2026",
      coordinator: "Lyc\xE9e Technique Paul Vincensini (Bastia, Corsica, France)",
      partners: [
        "Lyc\xE9e Technique Paul Vincensini (France) \u2013 Coordinator",
        "Mehmet \xD6z\xF6ncel Anadolu Lisesi (Adana, T\xFCrkiye)",
        "Palatul Copiilor Bac\u0103u (Romania)",
        "Alternative Learning Programme \u2013 ALP Paola (Malta)"
      ],
      goals: [
        "Raise awareness of childhood and adolescent obesity",
        "Promote healthy eating habits and balanced nutrition",
        "Encourage regular physical activity and traditional sports",
        "Develop intercultural cooperation between the four partner schools"
      ],
      website: "https://lateristoolatesaynotoobesitynow.lovable.app"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-partners.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var partners = [
  {
    country: "France",
    role: "Coordinator",
    school: "Lyc\xE9e Technique Paul Vincensini",
    city: "Bastia, Corsica",
    website: "https://lycee-paul-vincensini.web.ac-corse.fr/"
  },
  {
    country: "T\xFCrkiye",
    role: "Partner",
    school: "Mehmet \xD6z\xF6ncel Anadolu Lisesi",
    city: "Adana",
    website: "https://www.instagram.com/explore/locations/40157024/mehmet-ozoncel-anadolu-lisesi/"
  },
  {
    country: "Romania",
    role: "Partner",
    school: "Palatul Copiilor Bac\u0103u",
    city: "Bac\u0103u",
    website: "https://www.palatulcopiilorbacau.ro/"
  },
  {
    country: "Malta",
    role: "Partner",
    school: "Alternative Learning Programme (ALP Paola)",
    city: "Paola",
    website: "https://sites.google.com/view/alppaola/home"
  }
];
var list_partners_default = defineTool2({
  name: "list_partners",
  title: "List partner schools",
  description: "List the four partner schools taking part in the Erasmus+ project, with country, role, city, and website.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(partners, null, 2) }],
    structuredContent: { partners }
  })
});

// src/lib/mcp/tools/list-mobilities.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var mobilities = [
  {
    number: "LTTA 1",
    host_country: "T\xFCrkiye",
    host_city: "Adana",
    host_school: "Mehmet \xD6z\xF6ncel Anadolu Lisesi",
    theme: "Healthy eating & traditional sports"
  },
  {
    number: "LTTA 2",
    host_country: "Malta",
    host_city: "Paola",
    host_school: "ALP Paola",
    theme: "Physical activity & wellbeing"
  },
  {
    number: "LTTA 3",
    host_country: "France",
    host_city: "Bastia, Corsica",
    host_school: "Lyc\xE9e Technique Paul Vincensini",
    theme: "Mediterranean diet & lifestyle"
  },
  {
    number: "LTTA 4",
    host_country: "Romania",
    host_city: "Bac\u0103u",
    host_school: "Palatul Copiilor Bac\u0103u",
    theme: "Dissemination & project closure"
  }
];
var list_mobilities_default = defineTool3({
  name: "list_mobilities",
  title: "List mobilities & meetings",
  description: "List the project's Learning, Teaching and Training Activities (LTTAs) in chronological order, with host country, city, school, and theme.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(mobilities, null, 2) }],
    structuredContent: { mobilities }
  })
});

// src/lib/mcp/tools/list-timeline.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var timeline = [
  { date: "March 2025", type: "Milestone", title: "Project kick-off" },
  { date: "April 2025", type: "Activity", title: "Logo and Visual Identity contest" },
  { date: "April 2025", type: "Output", title: "Project website and social media launch" },
  { date: "May 2025", type: "Activity", title: "Preparatory activities for LTTA 1" },
  { date: "October 2025", type: "Mobility", title: "LTTA 1 \u2013 Adana, T\xFCrkiye" },
  { date: "November 2025", type: "Activity", title: "Post-LTTA 1 dissemination" },
  { date: "February 2026", type: "Mobility", title: "LTTA 2 \u2013 Paola, Malta" },
  { date: "April 2026", type: "Mobility", title: "LTTA 3 \u2013 Bastia, Corsica (France)" },
  { date: "May 2026", type: "Mobility", title: "LTTA 4 \u2013 Bac\u0103u, Romania" },
  { date: "July 2026", type: "Milestone", title: "Project completion & final report" }
];
var list_timeline_default = defineTool4({
  name: "list_timeline",
  title: "List project timeline",
  description: "Return the chronological project timeline from March 2025 to July 2026, with date, type (Milestone/Mobility/Activity/Output), and title.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(timeline, null, 2) }],
    structuredContent: { timeline }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "later-is-too-late-mcp",
  title: "LATER IS TOO LATE \u2014 Erasmus+ project MCP",
  version: "0.1.0",
  instructions: "Public read-only tools describing the Erasmus+ KA210 project 'LATER IS TOO LATE: SAY NO TO OBESITY NOW'. Use get_project_info for a general overview, list_partners for the four partner schools, list_mobilities for the LTTA mobilities, and list_timeline for the chronological milestones.",
  tools: [get_project_info_default, list_partners_default, list_mobilities_default, list_timeline_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
